### PR TITLE
UNO Cards

### PR DESCRIPTION
**Pull request by Vardaan-02**
Issue: #36

Card, Badge, Button Components are added all of them are highly customizable. Abstraction is followed is every Component. 

Button and Badge have different Variants so that they can be used directly out of the box by giving them variants. And of course you can pass className and ref to these components as these are forward ref component.

If the Card have another category to include it will be super easy as that part is also abstracted out of the main card.

Framer-Motion is used to add minimal animations.

If you have time then please read the code for better understanding.

Focused more on the reuseable part than the styling part

Dependency installed lucid react for icon, framer motion for animations, Prop types for validating props. YOu can remove the radix-ui/react/slot I finally decided to not include it.

Screenshot From 2024-12-18 13-46-27

### CODE REVIEW

**Comment by Vardaan-02** [comment]
If you need any improvements feel free to ask.

**Comment by Gamin8ing** [comment]
> If you need any improvements feel free to ask.

hello @Vardaan-02 thank you opening his PR, just to clarify this is not a streaming and playing platform, its just a platform for connecting various fandom, so we need the buttons the subheadings according to it, rest the designs are very good

**Comment by Vardaan-02** [comment]
should i change the text and make a pr again ?

**Comment by Gamin8ing** [comment]
whichever suits you better, but you could also commit new changes to this pr

**Comment by Vardaan-02** [comment]
will this work

**Comment by Vardaan-02** [comment]
will this work

**Comment by Vardaan-02** [comment]
there is some issue sharing the new image

i am sharing it on discord

**Comment by Gamin8ing** [comment]
Hello @Vardaan-02 thanks for this PR, but this wasn't up to the mark, but still ill be allotting partial points, hope u enjoyed it!

cheers

**Pull request merged**
